CREATE TABLE MEMBER(
	NUM NUMBER PRIMARY KEY.
	NAME VARCHAR2(20),
	ADDR VARCHAR2(50)
);

CREATE SEQUENCE MEMBER_SEQ

CREATE TABLE BOOK (
	NUM NUMBER PRIMARY KEY,
	TITLE VARCHAR2(50),
	AUTHOR VARCHAR2(50),
	PUBLISHER VARCHAR2(50)
);

CREATE SEQUENCE BOOK_SEQ;